redis:
  common:
    user: root
    pass: sZ!F5D5qHYZj8PFI
    maxOpenCon: 1000  #最大链接数
    maxIdleConns: 700 #最大空闲连接数
    conLiveTime: 3600 #超时时间
    pieceNum: 1  # 分片数量
  game:
    host1:
      ip: 127.0.0.1
      port: 25370
