server:
  release:
    node1: 127.0.0.1
    node2: 128.0.0.1
    node3: 129.0.0.1

logger:
  maxSize: 40960              # 文件大小限制,单位MB
  maxBackups: 100             # 最大保留日志文件数量
  maxKeepDay: 30              # 日志文件保留天数
  isCompress: false           # 是否压缩处理